remote_theme: pages-themes/slate@v0.2.0
gem "github-pages", group: :jekyll_plugins
title: Particle swarm optimization (PSO)
description: "The best implementation of PSO with OOP never seen by <a href = 'https://github.com/fegonzalez7'>@fegonzalez7</a>"
